<?php

return [
    // Основной массив постов
    'data' => [
        [
            'id' => 1,
            'title' => 'Введение в современный PHP',
            'slug' => 'vvedenie-v-sovremennyi-php',
            'excerpt' => 'В этой статье мы рассмотрим основные нововведения PHP 8.x...',
            'date' => '2024-03-15',
            'image_url' => '/storage/images/php-intro.jpg',
            'category' => 'PHP',
            'views' => 1250,
            'read_time' => 5,
        ],
        [
            'id' => 2,
            'title' => 'Laravel: лучшие практики',
            'slug' => 'laravel-luchshie-praktiki',
            'excerpt' => 'Разбираем архитектурные паттерны и лучшие практики в Laravel...',
            'date' => '2024-03-10',
            'image_url' => '/storage/images/laravel-best.jpg',
            'category' => 'Laravel',
            'views' => 980,
            'read_time' => 8,
        ],
        [
            'id' => 3,
            'title' => 'Docker для разработчиков',
            'slug' => 'docker-dlya-razrabotchikov',
            'excerpt' => 'Полное руководство по настройке Docker-окружения...',
            'date' => '2024-03-05',
            'image_url' => '/storage/images/docker-guide.jpg',
            'category' => 'DevOps',
            'views' => 2150,
            'read_time' => 12,
        ],
        [
            'id' => 4,
            'title' => 'Тестирование в Laravel',
            'slug' => 'testirovanie-v-laravel',
            'excerpt' => 'Unit, Feature и Browser тесты на реальных примерах...',
            'date' => '2024-02-28',
            'image_url' => '/storage/images/laravel-testing.jpg',
            'category' => 'Laravel',
            'views' => 760,
            'read_time' => 6,
        ],
        [
            'id' => 5,
            'title' => 'Оптимизация запросов к базе данных',
            'slug' => 'optimizatsiya-zaprosov-k-baze-dannyh',
            'excerpt' => 'Индексы, explain plan и другие техники оптимизации...',
            'date' => '2024-02-20',
            'image_url' => '/storage/images/db-optimization.jpg',
            'category' => 'Базы данных',
            'views' => 1890,
            'read_time' => 10,
        ],
        [
            'id' => 6,
            'title' => 'Vue.js и Laravel: идеальный дуэт',
            'slug' => 'vue-js-i-laravel-idealnyi-duet',
            'excerpt' => 'Создание SPA-приложений с использованием Laravel и Vue...',
            'date' => '2024-02-15',
            'image_url' => '/storage/images/vue-laravel.jpg',
            'category' => 'JavaScript',
            'views' => 1420,
            'read_time' => 9,
        ],
        [
            'id' => 7,
            'title' => 'REST API: проектирование и реализация',
            'slug' => 'rest-api-proektirovanie-i-realizatsiya',
            'excerpt' => 'Создаем масштабируемое REST API с нуля...',
            'date' => '2024-02-10',
            'image_url' => '/storage/images/rest-api.jpg',
            'category' => 'API',
            'views' => 2310,
            'read_time' => 11,
        ],
        [
            'id' => 8,
            'title' => 'Микросервисная архитектура',
            'slug' => 'mikroservisnaya-arhitektura',
            'excerpt' => 'Плюсы, минусы и практические примеры внедрения...',
            'date' => '2024-02-05',
            'image_url' => '/storage/images/microservices.jpg',
            'category' => 'Архитектура',
            'views' => 1750,
            'read_time' => 15,
        ],
        [
            'id' => 9,
            'title' => 'Git: продвинутые техники',
            'slug' => 'git-prodvinutye-tehniki',
            'excerpt' => 'Rebase, cherry-pick и другие команды для профессионалов...',
            'date' => '2024-01-30',
            'image_url' => '/storage/images/git-advanced.jpg',
            'category' => 'Инструменты',
            'views' => 890,
            'read_time' => 7,
        ],
        [
            'id' => 10,
            'title' => 'Оптимизация производительности PHP',
            'slug' => 'optimizatsiya-proizvoditelnosti-php',
            'excerpt' => 'Кэширование, профилирование и другие техники...',
            'date' => '2024-01-25',
            'image_url' => '/storage/images/php-performance.jpg',
            'category' => 'PHP',
            'views' => 1980,
            'read_time' => 8,
        ],
    ],

    // Данные пагинации (имитация)
    'pagination' => [
        'current_page' => 1,
        'per_page' => 10,
        'total' => 25, // Всего постов в "базе"
        'last_page' => 3,
        'links' => [
            [
                'url' => '/blog?page=1',
                'label' => '1',
                'active' => true,
            ],
            [
                'url' => '/blog?page=2',
                'label' => '2',
                'active' => false,
            ],
            [
                'url' => '/blog?page=3',
                'label' => '3',
                'active' => false,
            ],
        ],
        'first_page_url' => '/blog?page=1',
        'last_page_url' => '/blog?page=3',
        'next_page_url' => '/blog?page=2',
        'prev_page_url' => null,
        'from' => 1,
        'to' => 10,
    ],

    // Стандартные фильтры
    'filters' => [
        'title' => '',
        'date_from' => '',
        'date_to' => '',
        'sort_by' => 'date',
        'sort_direction' => 'desc',
    ],
];
